export const util = {
  ACTIVE: "ACTIVE",
};

export const creatingAccount = {
  CREATINGACC: "CREATINGACC",
  CREATINGACCSUCCESS: "CREATINGACCSUCCESS",
  CREATINGACCFAILED: "CREATINGACCFAILED",
};
export const login = {
  LOGIGNG: "LOGIGNG",
  LOGINSUCCESS: "LOGINSUCCESS",
  LOGINFAILED: "LOGINFAILED",
};
export const isLogged = {
  CHECKING: "CHECKING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
};
export const accUpdate = {
  UPDATING: "UPDATING",
  UPDATESUCCESS: "UPDATESUCCESS",
  UPDATEFAILD: "UPDATEFAILD",
};
export const addCatogery = {
  ADDIGN: "ADDIGN",
  ADDIGNSUCCESS: "ADDIGNSUCCESS",
  ADDINGFAILD: "ADDINGFAILD",
};
export const getCatogery = {
  GETING: "GETING",
  GETCATOGERYSUCESS: "GETCATOGERYSUCESS",
  GETCATOGERYFAILED: "GETCATOGERYFAILED",
};
export const deleteCatogery = {
  DELETING: "DELETING",
  DELETESUCCESS: "DELETESUCCESS",
  DELETEFAILD: "DELETEFAILD",
};
export const updateCatogery = {
  UPDATING: "UPDATING",
  UPDATESUCCESS: "UPDATESUCCESS",
  UPDATEFAILD: "UPDATEFAILD",
};
export const addProduct = {
  PRODUCTADDING: "PRODUCTADDING",
  PRODUCTADDINGSUCCESS: "PRODUCTADDINGSUCCESS",
  PRODUCTADDINGFAILD: "  PRODUCTADDINGFAILD",
};
export const getProduct = {
  GEINGPRODUCT: "GEINGPRODUCT",
  GETINGPRODUCTSUCCESS: "GETINGPRODUCTSUCCESS",
  PRODUCTGETTINGFAILS: "PRODUCTGETTINGFAILS",
};
